// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkGGdKPDJWBhwCP-L3AAkuoaTI6l1JzKI',
    appId: '1:107756355915:web:3951aceeea7e11bd79e8ce',
    messagingSenderId: '107756355915',
    projectId: 'fixmystreet-firebase',
    authDomain: 'fixmystreet-firebase.firebaseapp.com',
    storageBucket: 'fixmystreet-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0WBitHCQBiNsg2oX4G_Y_GdJmYnMoSzU',
    appId: '1:107756355915:android:bfa50e08e76c974879e8ce',
    messagingSenderId: '107756355915',
    projectId: 'fixmystreet-firebase',
    storageBucket: 'fixmystreet-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7KS6XsXx_cLTOEMHuTgdba0icc0fMT_w',
    appId: '1:107756355915:ios:f89a71078bdd5fc779e8ce',
    messagingSenderId: '107756355915',
    projectId: 'fixmystreet-firebase',
    storageBucket: 'fixmystreet-firebase.firebasestorage.app',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7KS6XsXx_cLTOEMHuTgdba0icc0fMT_w',
    appId: '1:107756355915:ios:f89a71078bdd5fc779e8ce',
    messagingSenderId: '107756355915',
    projectId: 'fixmystreet-firebase',
    storageBucket: 'fixmystreet-firebase.firebasestorage.app',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkGGdKPDJWBhwCP-L3AAkuoaTI6l1JzKI',
    appId: '1:107756355915:web:231a78457da280c279e8ce',
    messagingSenderId: '107756355915',
    projectId: 'fixmystreet-firebase',
    authDomain: 'fixmystreet-firebase.firebaseapp.com',
    storageBucket: 'fixmystreet-firebase.firebasestorage.app',
  );

}